#encoding: UTF-8

source "https://github.com/agile-swift/Specs.git"
source "https://github.com/CocoaPods/Specs.git"

use_frameworks!

target 'ATDebug_Example' do
  pod 'ATDebug', :path => '../'
  pod 'ATFoundation', :path => '../../ATFoundation'
  pod 'ATUIKit', :path => '../../ATUIKit'

  target 'ATDebug_Tests' do
    inherit! :search_paths

    
  end
end
